# Site settings
title: execbit.ru
email: zobnin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Личный блог о работе
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://execbit.ru" # the base hostname & protocol for your site
twitter_username: ezobnin
github_username:  zobnin

# Build settings
markdown: kramdown
