# Site settings
title: Back to the root
email: zobnin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Блог об Android и UNIX
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zobnin.github.io" # the base hostname & protocol for your site
twitter_username: ezobnin
github_username:  zobnin

# Build settings
markdown: kramdown
